version: '3'

services:
  db:
    image: postgres
    container_name: meu-servidor-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: seu_usuario_do_banco
      POSTGRES_PASSWORD: sua_senha_do_banco
      POSTGRES_DB: nome_do_banco_de_dados
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
